digitalportrait/digitalportrait/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('portrait/', include('portrait.urls')),
    path('directories/', include('directories.urls')),
    path('tasks/', include('tasks.urls')),
]

digitalportrait/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
]

digitalportrait/tasks/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='tasks'),
    path('<int:id>/', views.task, name='task'),
    path('subject/<int:id>/<int:subject_id>/', views.subject, name='subject'),
    path('process/<int:id>/', views.process, name='task_process'),
    path('all/', views.all, name='tasks_children'),
]

digitalportrait/tasks/models.py
from django.db import models
from django.contrib.auth.models import User

class Tasks(models.Model):
    TASK_PERSONAL      = 1
    TASK_COGNITIVE     = 2
    TASK_REGULATORY    = 3
    TASK_COMMUNICATIVE = 4
    TASK_SUBJECT       = 5

    TASKS_CHOICES = (
        (TASK_PERSONAL, 'Личностные УУД'),
        (TASK_COGNITIVE, 'Познавательные УУД'),
        (TASK_REGULATORY, 'Регулятивные УУД'),
        (TASK_COMMUNICATIVE, 'Коммуникативные УУД'),
        (TASK_SUBJECT, 'Предметные УУД'),
    )

    task_id  = models.SmallIntegerField(choices=TASKS_CHOICES, null=True, blank=True)
    children = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = "tbl_tasks"

class TasksPersonal(models.Model):
    task       = models.ForeignKey(Tasks, on_delete=models.CASCADE)
    discipline = models.TextField(null=True, blank=True)

    class Meta:
        db_table = "tbl_tasks_personal"

class TasksObjective(models.Model):
    OBJECTIVE_MATH    = 1
    OBJECTIVE_RUSSIAN = 2
    OBJECTIVE_READ    = 3
    OBJECTIVE_WORLD   = 4

    OBJECTIVE_CHOICES = (
        (OBJECTIVE_MATH, 'Математика'),
        (OBJECTIVE_RUSSIAN, 'Русския язык'),
        (OBJECTIVE_READ, 'Литературное чтение'),
        (OBJECTIVE_WORLD, 'Окружающий мир'),
    )

    objective_id  = models.SmallIntegerField(choices=OBJECTIVE_CHOICES, null=True, blank=True)
    title         = models.TextField(null=True, blank=True)
    class Meta:
        db_table = "tbl_tasks_objective"

class TasksObjectiveOptions(models.Model):
    objective  = models.ForeignKey(TasksObjective, on_delete=models.CASCADE)
    option     = models.TextField(null=True, blank=True)
    status_id  = models.BooleanField(null=True, blank=True)

    class Meta:
        db_table = "tbl_tasks_objective_options"

digitalportrait/tasks/forms.py
from django import forms
from tasks.models import Tasks, TasksPersonal
from profiles.models import Profiles

class ChildrenModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.fullname

class TaskCreateForm(forms.Form):
    task_id  = forms.ChoiceField(label=False, choices=Tasks.TASKS_CHOICES, widget=forms.RadioSelect)
    children = ChildrenModelChoiceField(label='Выбрать ребенка', queryset=Profiles.objects.filter(role_id=Profiles.ROLE_CHILDREN).order_by('-fullname').all(), to_field_name='user_id')

    def __init__(self, *args, **kwargs):
        super(TaskCreateForm, self).__init__(*args, **kwargs)

        self.fields['task_id'].widget.attrs = {
            'class': 'form-control',
        }
        self.fields['children'].widget.attrs = {
            'class': 'form-control',
        }

    class Meta:
        model = Tasks
        fields = '__all__'

class TaskPersonalCreateForm(forms.Form):
    discipline = forms.CharField(label='Введите дисциплину', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(TaskPersonalCreateForm, self).__init__(*args, **kwargs)
        self.fields['discipline'].widget.attrs = {
            'class': 'form-control',
        }

    class Meta:
        model = TasksPersonal
        fields = '__all__'

digitalportrait/tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from tasks.forms import TaskCreateForm, TaskPersonalCreateForm
from tasks.models import Tasks, TasksPersonal, TasksObjective
from django.contrib.auth.models import User
from profiles.models import Profiles

@login_required
def index(request):
    if request.user.profiles.role_id is not Profiles.ROLE_EDUCATOR:
        return redirect('home')
    if request.method == 'POST':
        form = TaskCreateForm(request.POST)
        if form.is_valid():
            task          = Tasks()
            children      = form.cleaned_data.get('children')
            task.children = User.objects.get(id=children.user_id)
            task.task_id  = form.cleaned_data.get('task_id')
            task.save()
            return redirect('task', id=task.id)
    else:
        form = TaskCreateForm()

    return render(request, 'tasks/index.html', {'form': form})


@login_required
def task(request, id):
    if request.user.profiles.role_id is not Profiles.ROLE_EDUCATOR:
        return redirect('home')
    queryset = Tasks.objects.filter(id=id)
    task = get_object_or_404(queryset)

    if task.task_id is Tasks.TASK_PERSONAL:
        disciplines = TasksPersonal.objects.filter(task=task).order_by('-id').all()
        if request.method == 'POST':
            form = TaskPersonalCreateForm(request.POST)
            if form.is_valid():
                model            = TasksPersonal()
                model.discipline = form.cleaned_data.get('discipline')
                model.task       = task
                model.save()
        else:
            form = TaskPersonalCreateForm()
        return render(request, 'tasks/personal.html', {'task':task, 'form': form, 'disciplines': disciplines})

    if task.task_id is Tasks.TASK_SUBJECT:
        return render(request, 'tasks/subject.html', {'task':task,'model':TasksObjective})


    return render(request, 'tasks/task.html', {})

@login_required
def subject(request, id, subject_id):
    if request.user.profiles.role_id is not Profiles.ROLE_EDUCATOR:
        return redirect('home')

    title    = TasksObjective.OBJECTIVE_CHOICES[subject_id-1][1]
    subjects = TasksObjective.objects.filter(objective_id=subject_id).all()

    return render(request, 'tasks/subject_options.html', {'title':title,'subjects':subjects})

@login_required
def all(request):
    if request.user.profiles.role_id is not Profiles.ROLE_CHILDREN:
        return redirect('home')

    tasks = Tasks.objects.filter(children=request.user).all()

    return render(request, 'tasks/all.html', {'tasks':tasks, 'model': Tasks})

@login_required
def process(request, id):
    queryset = Tasks.objects.filter(id=id)
    task = get_object_or_404(queryset)

    if request.user != task.children:
        return redirect('home')

    if task.task_id is Tasks.TASK_PERSONAL:
        disciplines = TasksPersonal.objects.filter(task=task).order_by('-id').all()
        return render(request, 'tasks/process/personal.html', {'disciplines': disciplines})

    return render(request, 'tasks/task.html', {})

digitalportrait/templates/tasks/all.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="row mt-5 pb-5 pt-5">
        <div class="col-sm-10 m-auto">
            {% if tasks %}
                <div class="tasks">
                    {% for obj in tasks %}
                        <a href="{% url 'task_process' obj.id %}">{{ obj.get_task_id_display }}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

digitalportrait/templates/tasks/index.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-8 m-auto">
            <div class="mt-5 pt-5 pb-5">
                <form method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}

                    {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                    {% endfor %}

                    <div class="form-group">
                        {{ form.children.label_tag }}
                        {{ form.children }}
                        <small class="form-text text-muted">{{ form.children.errors }}</small>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            {% for task in form.task_id %}
                                <div class="col-sm-4 label-tasks">
                                    {{ task.tag }}
                                    <label for="{{ task.id_for_label  }}">{{ task.choice_label }}</label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Выбрать</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

digitalportrait/templates/tasks/personal.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="row mt-5 pb-5 pt-5">
        <div class="col-sm-10 m-auto">
            <h4>{{task.children.profiles.fullname}}</h4>
            <h4>Личностные УУД</h4>
        </div>

        <div class="col-sm-10 m-auto">
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}

                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field.errors }}
                    {{ hidden_field }}
                {% endfor %}

                <div class="form-group">
                    {{ form.discipline.label_tag }}
                    {{ form.discipline }}
                    <small class="form-text text-muted">{{ form.discipline.errors }}</small>
                </div>

                <button type="submit" class="btn btn-primary">Добавить</button>
            </form>
        </div>
    </div>

    {% if disciplines %}
        <div class="row mt-5 pt-5 pb-5">
            <div class="col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Дисциплина</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in disciplines %}
                            <tr>
                                <td>{{obj.discipline}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
{% endblock %}

digitalportrait/templates/tasks/subject.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="row mt-5 pb-5 pt-5">
        <div class="col-sm-10 m-auto">
            <h4>Предметные УУД</h4>
        </div>

        <div class="col-sm-10 m-auto mt-5 py-5 text-center">
            <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'subject' task.id model.OBJECTIVE_MATH %}">Математика</a></li>
                <li class="list-group-item"><a href="{% url 'subject' task.id model.OBJECTIVE_RUSSIAN %}">Русския язык</a></li>
                <li class="list-group-item"><a href="{% url 'subject' task.id model.OBJECTIVE_READ %}">Литературное чтение</a></li>
                <li class="list-group-item"><a href="{% url 'subject' task.id model.OBJECTIVE_WORLD %}">Окружающий мир</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

digitalportrait/templates/tasks/subject_options.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="row mt-5 pb-5 pt-5">
        <div class="col-sm-10 m-auto">
            <h4>Предметные УУД</h4>
            <h5 class="mt-3">{{title}}</h5>
        </div>

        <div class="d-none">
            <div>
                <input type="text" name="question[]">
            </div>
            <div>
                Варианты ответов:
            </div>
            <div>
                <div>
                    <input type="text" name="answer[]">
                    <input type="checkbox" name="is_true[]">
                </div>
            </div>
        </div>

        <div class="col-sm-10 m-auto mt-5 py-5 text-center">
            <form method="post">
                {% for subject in subjects %}
                    <div>
                        <input type="text" name="question[]" value="{{subject.title}}">
                    </div>
                    <div>
                        Варианты ответов:
                    </div>
                    <div>
                        {% for option in subject__tasksobjectiveoptions.all %}
                            <div>
                                <input type="text" name="answer[]" value="{{option.}}">
                                <input type="checkbox" name="is_true[]">
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </form>
        </div>
    </div>
{% endblock %}